name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme LibAuk build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
    - name: Run tests
      run: xcodebuild -scheme LibAuk test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
