name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme LibAuk build -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
    - name: Run tests
      run: xcodebuild -scheme LibAuk test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
